create table users(
    id integer generated by DEFAULT as IDENTITY,
    email varchar(100) not NULL,
    name varchar(50) not null,
    phone varchar(50), 
    foreign key role references user_roles(id),
    password varchar(300) not null,
    createat TIMESTAMP(2), 
    updateat TIMESTAMP(2),
    PRIMARY KEY (email)
)

create table user_roles (
    id INTEGER generated by DEFAULT as IDENTITY,
    role_name varchar(50) not null, 
    createat TIMESTAMP(2), 
    updateat TIMESTAMP(2),
    PRIMARY KEY (id)
)

create table flowers (
    id INTEGER generated BY DEFAULT as IDENTITY,
    flower_name VARCHAR(100) not NULL,
    flower_amount INTEGER not NULL,
    flower_origin VARCHAR(100),
    flower_color VARCHAR(50),
    createat TIMESTAMP(2), 
    updateat TIMESTAMP(2),
    PRIMARY KEY (id)
)
